"""Publish final assets into a front-end app.

1. Back up whatever is about to be overwritten into `backup/<timestamp>/`.
2. Copy `assets/final/*.png` to `<app>/src/assets/bigviz/<slug>/`.
3. Write `<app>/src/views/<Name>/assets.manifest.ts`, a typed module that
   imports every image and exports `{ id, src, width, height, aspect, trim }`.
"""

from __future__ import annotations

import json
import os
import re
import shutil
from datetime import datetime
from pathlib import Path

from bigviz.manifest import build_manifest, load_manifest
from bigviz.spec import SLUG_RE, Spec

TS_HEADER = """\
// Generated by `bigviz publish` from {slug}/assets/final/manifest.json. Do not edit by hand.
/* eslint-disable */

export interface BigVizAsset {{
  id: string
  src: string
  width: number
  height: number
  aspect: number
  /** Transparent margin around the solid body, as fractions of width / height. */
  trim: {{ l: number; t: number; r: number; b: number }}
}}
"""


def view_name(slug: str) -> str:
    """`safety-points` -> `SafetyPoints`."""
    return "".join(p.capitalize() for p in slug.split("-"))


def ident(asset_id: str) -> str:
    """`center-hub` -> `centerHub` (safe TS identifier)."""
    parts = re.split(r"[^A-Za-z0-9]+", asset_id)
    name = parts[0].lower() + "".join(p.capitalize() for p in parts[1:])
    return f"img_{name}" if not name or name[0].isdigit() else name


def _num(v: float) -> str:
    return str(int(v)) if float(v).is_integer() else repr(round(float(v), 4))


def render_ts(slug: str, assets: list[dict], import_dir: str) -> str:
    """TypeScript source for `assets.manifest.ts`. `import_dir` is relative to the view dir."""
    lines = [TS_HEADER.format(slug=slug)]
    names = []
    seen: dict[str, str] = {}
    for a in assets:
        # ids/file names come from files on disk: only slug-safe names may reach generated code
        if not SLUG_RE.fullmatch(a["id"]) or a["file"] != f"{a['id']}.png":
            raise ValueError(f"asset file '{a['file']}' must be named <kebab-case-id>.png")
        name = ident(a["id"])
        if name in seen:
            raise ValueError(f"asset ids '{seen[name]}' and '{a['id']}' map to the same identifier")
        seen[name] = a["id"]
        names.append((name, a))
        src = json.dumps(f"{import_dir}/{a['file']}")
        lines.append(f"import {name}Src from {src}")
    lines.append("")
    lines.append("export const assets = {")
    for name, a in names:
        t = a["trim"]
        lines.append(
            f"  {json.dumps(a['id'])}: {{ id: {json.dumps(a['id'])}, src: {name}Src, width: {a['width']}, "
            f"height: {a['height']}, aspect: {_num(a['aspect'])}, "
            f"trim: {{ l: {_num(t['l'])}, t: {_num(t['t'])}, r: {_num(t['r'])}, b: {_num(t['b'])} }} }},"
        )
    lines.append("} satisfies Record<string, BigVizAsset>")
    lines.append("")
    lines.append("export type BigVizAssetId = keyof typeof assets")
    lines.append("export default assets")
    return "\n".join(lines) + "\n"


def publish(spec: Spec, app: Path | str, name: str | None = None,
            now: datetime | None = None) -> dict:
    """Back up, copy finals, write the manifest module. Returns a summary dict."""
    app = Path(app).resolve()
    if not (app / "src").is_dir():
        raise FileNotFoundError(f"{app} has no src/ directory (is --app the front-end root?)")
    final_dir = spec.workspace / "assets" / "final"
    finals = sorted(final_dir.glob("*.png"))
    if not finals:
        raise FileNotFoundError(f"no final assets in {final_dir} (run `bigviz regen` first)")
    build_manifest(spec)
    manifest = load_manifest(spec)

    name = name or view_name(spec.slug)
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_-]*", name):
        raise ValueError(f"--name must be a plain view folder name, got '{name}'")
    asset_dir = app / "src" / "assets" / "bigviz" / spec.slug
    view_dir = app / "src" / "views" / name
    ts_path = view_dir / "assets.manifest.ts"

    stamp = (now or datetime.now()).strftime("%Y%m%d-%H%M%S")
    backup = spec.workspace / "backup" / stamp
    n = 1
    while backup.exists():
        n += 1
        backup = spec.workspace / "backup" / f"{stamp}-{n}"
    backup.mkdir(parents=True)
    if asset_dir.is_dir():
        shutil.copytree(asset_dir, backup / "assets")
    if ts_path.is_file():
        shutil.copy2(ts_path, backup / "assets.manifest.ts")
    (backup / "publish.json").write_text(json.dumps({
        "app": str(app), "asset_dir": str(asset_dir), "manifest_ts": str(ts_path),
        "files": [p.name for p in finals], "timestamp": stamp,
    }, indent=2) + "\n", encoding="utf-8")

    asset_dir.mkdir(parents=True, exist_ok=True)
    for old in asset_dir.glob("*.png"):
        old.unlink()  # backed up above; avoid stale images from earlier publishes
    for p in finals:
        shutil.copy2(p, asset_dir / p.name)

    view_dir.mkdir(parents=True, exist_ok=True)
    rel = Path(os.path.relpath(asset_dir, view_dir)).as_posix()
    rel = rel if rel.startswith(".") else f"./{rel}"
    ts_path.write_text(render_ts(spec.slug, manifest["assets"], rel), encoding="utf-8")
    return {"backup": str(backup), "asset_dir": str(asset_dir), "manifest_ts": str(ts_path),
            "count": len(finals)}
