// Generated by `bigviz publish` — do not edit by hand. Re-run `bigviz manifest && bigviz publish`.
// slug: example · source: assets/final/manifest.json
// trim = transparent margin (alpha <= 8) / width (l, r) or / height (t, b)
import type { BigVizAsset } from '@/screen/types'
import centerHub from '@/assets/bigviz/example/center-hub.png'
import goods1 from '@/assets/bigviz/example/goods-1.png'
import goods2 from '@/assets/bigviz/example/goods-2.png'
import goods3 from '@/assets/bigviz/example/goods-3.png'
import goods4 from '@/assets/bigviz/example/goods-4.png'
import goods5 from '@/assets/bigviz/example/goods-5.png'
import kpiCoins from '@/assets/bigviz/example/kpi-coins.png'
import kpiExchangeCount from '@/assets/bigviz/example/kpi-exchange-count.png'
import kpiGift from '@/assets/bigviz/example/kpi-gift.png'
import kpiUsers from '@/assets/bigviz/example/kpi-users.png'
import ringCart from '@/assets/bigviz/example/ring-cart.png'
import ringCoins from '@/assets/bigviz/example/ring-coins.png'
import ringGift from '@/assets/bigviz/example/ring-gift.png'
import ringHelmet from '@/assets/bigviz/example/ring-helmet.png'
import teamPodium from '@/assets/bigviz/example/team-podium.png'

export const ASSETS = {
  'center-hub': { id: 'center-hub', src: centerHub, width: 1000, height: 945, aspect: 1.0582, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'goods-1': { id: 'goods-1', src: goods1, width: 256, height: 256, aspect: 1, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'goods-2': { id: 'goods-2', src: goods2, width: 256, height: 256, aspect: 1, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'goods-3': { id: 'goods-3', src: goods3, width: 256, height: 256, aspect: 1, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'goods-4': { id: 'goods-4', src: goods4, width: 256, height: 256, aspect: 1, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'goods-5': { id: 'goods-5', src: goods5, width: 256, height: 256, aspect: 1, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'kpi-coins': { id: 'kpi-coins', src: kpiCoins, width: 384, height: 357, aspect: 1.0756, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'kpi-exchange-count': { id: 'kpi-exchange-count', src: kpiExchangeCount, width: 329, height: 384, aspect: 0.8568, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'kpi-gift': { id: 'kpi-gift', src: kpiGift, width: 384, height: 380, aspect: 1.0105, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'kpi-users': { id: 'kpi-users', src: kpiUsers, width: 384, height: 314, aspect: 1.2229, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'ring-cart': { id: 'ring-cart', src: ringCart, width: 456, height: 480, aspect: 0.95, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'ring-coins': { id: 'ring-coins', src: ringCoins, width: 480, height: 460, aspect: 1.0435, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'ring-gift': { id: 'ring-gift', src: ringGift, width: 476, height: 480, aspect: 0.9917, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'ring-helmet': { id: 'ring-helmet', src: ringHelmet, width: 469, height: 480, aspect: 0.9771, trim: { l: 0, t: 0, r: 0, b: 0 } },
  'team-podium': { id: 'team-podium', src: teamPodium, width: 1898, height: 810, aspect: 2.3432, trim: { l: 0.0042, t: 0.0136, r: 0.0016, b: 0 } }
} as const satisfies Record<string, BigVizAsset>

export type AssetId = keyof typeof ASSETS
